version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  jupyterlab:
    network_mode: host
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace
  spark-master:
    network_mode: host
    image: spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
  spark-worker-1:
    network_mode: host
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=8
      - SPARK_WORKER_MEMORY=32G
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
  spark-worker-2:
    network_mode: host
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=8
      - SPARK_WORKER_MEMORY=32G
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
  spark-worker-3:
    network_mode: host
    image: spark-worker
    container_name: spark-worker-3
    environment:
      - SPARK_WORKER_CORES=8
      - SPARK_WORKER_MEMORY=32G
    ports:
      - 8083:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
  spark-worker-4:
    network_mode: host
    image: spark-worker
    container_name: spark-worker-4
    environment:
      - SPARK_WORKER_CORES=8
      - SPARK_WORKER_MEMORY=32G
    ports:
      - 8084:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
  spark-worker-5:
    network_mode: host
    image: spark-worker
    container_name: spark-worker-5
    environment:
      - SPARK_WORKER_CORES=8
      - SPARK_WORKER_MEMORY=32G
    ports:
      - 8085:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
